# -*- coding: utf-8 -*-
"""exam of aimlipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nztG9kYnBWZX0Azqcw5SsWI8s9EDsdtp
"""

import pandas as pd
import numpy as np
from scipy import stats

data=pd.read_csv("//content/titanic.csv")
data.head()
data.shape
data.info()
data.isnull().sum()

mean=np.mean(data['Age'])
median=np.median(data['Age'])
mode=stats.mode(data['Age'],keepdims=True).mode[0]
mean1=np.mean(data['Fare'])
median1=np.median(data['Fare'])
mode1=stats.mode(data['Fare'],keepdims=True).mode[0]
print("central tendancy")
print("maen of Age=",mean)
print("median of Age=",median)
print("mode of Age=",mode)
print("maen of Fare=",mean1)
print("median of Fare=",median1)
print("mode of Fare=",mode1)

null_value=data['Age'].isnull().sum()
fitted_data=data['Age'].fillna(data['Age'].mean(numeric_only=True))
null_value,fitted_data.head()

import seaborn as sns
import matplotlib.pyplot as plt
mean=np.mean(data['Age'])
std=np.std(data['Age'])
print('mean of Age:',mean)
print('standard deviation of Age:',std)
threshold=3
outliers=[]
for i in data['Age']:
  z_score=(i-mean)/std
  if z_score > threshold:
    outliers.append(i)
print('outliers is=',outliers)
sns.boxplot(data['Age'])
plt.ylabel('Age')
plt.title('boxplot')
plt.show()